#+title: Programozási technológia 1 - 2. beadandó
#+subtitle: 7. feladat - Áttörés
#+author: Sana Norbert
#+email: neilus@elte.hu

* Feladatkiírás
*7. Áttörés*
Készítsünk  programot,  amellyel  a  következő  kétszemélyes  já
tékot  lehet játszani.  Adott  egy /n × n/
  mezőből  álló  tábla,  ahol  a  két  játékos  bábúi  egymással  s
zemben  helyezkednek  el,  két 
sorban (pont, mint egy sakktáblán, így mindkét játékos /2n/
 bábuval rendelkezik, ám mindegyik 
bábu ugyanolyan típusú). A játékos bábúival csak előre léphet e
gyenesen, vagy átlósan egy 
mezőt (azaz oldalra, és hátra felé nem léphet), és hasonlóan 
ütheti a másik játékos bábúját 
előre átlósan (egyenesen nem támadhat). Az a játékos győz, aki e
lőször átér a játéktábla másik 
végére egy bábuval. 

A  program  biztosítson  lehetőséget  új  játék  kezdésére  a  tá
blaméret  megadásával  (6×6,  8×8, 
10×10), és ismerje fel, ha vége a játéknak. Ekkor jelenítse me
g, melyik játékos győzött, majd 
automatikusan kezdjen új játékot. 
